worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

stream {
    # WebSocket از Worker میاد روی 8080
    # تبدیل به TCP و فوروارد به Xray روی 12889
    server {
        listen 8080;
        proxy_pass 127.0.0.1:12889;
        proxy_connect_timeout 10s;
        proxy_timeout 300s;
    }
}
